# https://alacritty.org/config-alacritty.html

shell:
  program: /bin/zsh
  args:
  - -l

env:
  # for true color support
  # https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
  TERM: xterm-256color

window:
  startup_mode: Fullscreen

# DOWNLOAD HERE: https://www.nerdfonts.com/font-downloads
# must be a "Nerd Font" for icons to work on nvim-tree
font:
  size: 14.0
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold

scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 10000

mouse:
  double_click: {threshold: 300}
  triple_click: {threshold: 300}
  hide_when_typing: true
  hints:
    launcher:
      program: open
    modifiers: None
  copy_on_selection: true
  save_to_clipboard: true

selection:
  save_to_clipboard: true 
