# https://github.com/ianyh/Amethyst/blob/v0.22.1/.amethyst.sample.yml

layouts:
  - fullscreen

# first mod (default option + shift).
mod1:
  - command
  - shift
  # - control
  # - command

# second mod (default option + shift + control).
mod2:
  - command
  - shift
  - control
  # - command

# move to the next layout in the list.
cycle-layout:
  mod: mod1
  key: z

# true to display the name of the layout when a new layout is selected (default true).
enables-layout-hud: true

# true if menu bar icon should be hidden (default false).
hide-menu-bar-icon: false

# true if screen frames should exclude the status bar. false if the screen frames should include the status bar (default false).
# NOTE: this doesn't seem to work as there's still a gap when the menu bar is collapsed
ignore-menu-bar: true


