# https://github.com/ianyh/Amethyst/blob/v0.22.1/.amethyst.sample.yml
# NOTE: sometimes for options to apply, you must run: 'defaults delete com.amethyst.Amethyst.plist' and then start again

layouts:
  - fullscreen

# true to display the name of the layout when a new layout is selected (default true).
enables-layout-hud: true

# true if menu bar icon should be hidden (default false).
hide-menu-bar-icon: false

# Padding to apply between windows and the top edge of the screen (in px, default 0).
screen-padding-top: 0

# NOTE: this doesn't seem to work as there's still a gap when the menu bar is collapsed
# true if screen frames should exclude the status bar. false if the screen frames should include the status bar (default false).
# ignore-menu-bar: true

# NOTE: for now, i'm just using hammerspoon to navigate apps instead of cycling with amethyst
# NOTE: amethyst is just used for tiling config
# NOTE: the options set below can be ignored

# first mod (default option + shift).
mod1:
  - command
  - shift
  # enable the 2 below this so we don't get clashes with hammerspoon
  - control
  - command

# second mod (default option + shift + control).
mod2:
  - command
  - shift
  - control
  # - command

# focus the next window in the list going counter-clockwise.
focus-ccw:
  mod: mod1
  key: j

# focus the next window in the list going clockwise.
focus-cw:
  mod: mod1
  key: k

# move to the next layout in the list.
cycle-layout:
  mod: mod1
  key: z


